name: Build Unsigned IPA

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
      
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.4'
      
      - name: Build Unsigned IPA (No .p12 required)
        run: |
          xcodebuild -version
          chmod +x ./build_unsigned.sh
          ./build_unsigned.sh > build.log 2>&1
          
      - name: Upload log on failure
        if: failure()
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@bot.com"
          git add build.log
          git commit -m "update log" || true
          git push || true
      
      - name: Prepare eSign ready IPA
        run: |
          chmod +x ./build_esign_ready_ipa.sh
          ./build_esign_ready_ipa.sh build/HYper-Regedit-Key-Enabled-unsigned.ipa
      
      - name: Upload Unsigned IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: OGIOS-Unsigned-IPA
          path: build/HYper-Regedit-Key-Enabled-unsigned.ipa


